name: Validate kubernetes-kubectl.json

on:
  pull_request:
    branches:
      - main
    paths:
      - kubernetes-kubectl.json
      - .github/workflows/renovate-kubernetes-kubectl.yaml
  push:
    branches:
      - main
    paths:
      - kubernetes-kubectl.json
      - .github/workflows/renovate-kubernetes-kubectl.yaml
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.3
        with:
          config_file_path: kubernetes-kubectl.json
